@echo off
rem CalibGuard GUI one-click build (PyInstaller onefile + release assembly + zip).
setlocal
cd /d "%~dp0"

rem ---- step 1: embedded uv.exe must exist (see T-G2 for uv 0.5.11) ----
if not exist "tools\uv.exe" (
    echo [ERROR] tools\uv.exe not found. Obtain uv 0.5.11 first ^(T-G2^).
    exit /b 1
)
if not exist ".venv\Scripts\python.exe" (
    echo [ERROR] .venv not found. Run launcher.py once first, or install dev deps.
    exit /b 1
)

rem ---- step 2: build onefile exe (spec file is generated by PyInstaller) ----
".venv\Scripts\python.exe" -m PyInstaller --noconfirm --onefile --name CalibGuard --add-binary "tools/uv.exe;tools" launcher.py
if errorlevel 1 (
    echo [ERROR] PyInstaller failed.
    exit /b 1
)

rem ---- step 3: assemble release/ ----
if exist release rmdir /s /q release
mkdir release
copy /y "dist\CalibGuard.exe" "release\CalibGuard.exe" >nul
copy /y server.py "release\server.py" >nul
copy /y audit_service.py "release\audit_service.py" >nul
copy /y requirements-gui.txt "release\requirements-gui.txt" >nul
copy /y README.txt "release\README.txt" >nul
mkdir "release\web"
copy /y "web\index.html" "release\web\index.html" >nul
mkdir "release\calibguard"
copy /y "calibguard\*.py" "release\calibguard\" >nul
xcopy /e /i /y /q "models" "release\models" >nul
if errorlevel 1 (
    echo [ERROR] failed to copy models/ into release/.
    exit /b 1
)

rem ---- step 4: zip the release folder ----
if exist "dist\CalibGuard-GUI.zip" del /q "dist\CalibGuard-GUI.zip"
powershell -NoProfile -Command "Compress-Archive -Path 'release\*' -DestinationPath 'dist\CalibGuard-GUI.zip' -Force"
if errorlevel 1 (
    echo [ERROR] zip failed.
    exit /b 1
)

echo [OK] release\ ready, package: dist\CalibGuard-GUI.zip
endlocal
